// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();

const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });

router.post("/login", dataController.login);
router.post("/forgetPassword", dataController.forgetPassword);
router.post('/verify-otp', dataController.verifyOtp);
router.post("/signup", dataController.signUp);
router.post("/city", dataController.getCity)
router.post("/variant", dataController.getvariant)
router.post("/uom", dataController.getuom)
router.post("/country", dataController.getCountry)
router.post("/state", dataController.getState)
router.post("/status", dataController.getStatus)
router.post("/Shift", dataController.getShift)
router.post("/Transaction", dataController.getTransaction)
router.post("/gender", dataController.getGender)
router.post("/Loginorout", dataController.getLoginorout)
router.post("/add", upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.addData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.get ("/userData", dataController.getAlluserData)
router.get("/WareHouseData",dataController.getAllWareHouseData)
router.post("/AddWareHousedata",dataController.AddWareHouseData)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/userdelete", dataController.UserdeleteData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.post("/warehouseupdate", dataController.WareHousesaveEditedData)
router.get("/attrihdrdata",dataController.getAllattributehdrData)
router.post("/addattriData",dataController.addattrihdrData)
router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.get("/hdrcode", dataController.gethdrcode)
router.post("/taxtype", dataController.gettaxtype)
router.post("/delPer", dataController.getDeletepermission)
router.post("/regbrand", dataController.getregisterbrand)
router.post("/ourbrand", dataController.getourbrand)
router.post("/TaxHdrData", dataController.getAllTaxHdrData)
router.post("/addTaxHdrData", dataController.addTaxHdrData)
router.get("/TaxDetailsData", dataController.getAllTaxDetailsData)
router.post("/addTaxDetailsData",dataController.addTaxDetailsData)
router.post("/updTaxDetailsData",dataController.updtaxdetaildata)
router.get("/ItemBrandData",dataController.getAllItemBrandData)
router.post("/delItemBrandData",dataController.deleteItemData)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.post("/warehousedelete",dataController.WareHousedeleteData)
router.get("/VendorHdrData",dataController.getAllVendorHdrData)
router.post("/addVendorHdrData",dataController.addVendorHdrData)
router.get("/VendorDetData", dataController.getAllVendorDetData)
router.post("/addVendorDetData",dataController.addVendorDetData)
router.post("/updvendordetData",dataController.updvendordetData)
router.post("/deleteVendorData",dataController.VendordeleteData)
router.post("/vendorcode",dataController.getvendorcode)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.get("/usercode",dataController.getUsercode)
router.post("/Usertype", dataController.getUsertype)
router.get("/Companyno",dataController.getCompanyno)
router.get("/locationno",dataController.getLocationno)
router.post("/paytype", dataController.getPaytype)
router.post("/purchasetype", dataController.getPurchasetype)
router.post("/salestype", dataController.getSalestype)
router.post("/ordertype", dataController.getordertype)
router.post("/roleid", dataController.getroleid)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/itemsearchdata",dataController.getitemsearchdata)
router.post("/warehouseSearchdata",dataController.getwarehouseSearchdata)
router.post("/taxpercenttype",dataController.gettypeperdata)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/location_no",dataController.locationsaveEditedData)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/itempursearchdata",dataController.getitempursearchdata)
router.post("/getpursearchdata",dataController.getpursearchdata)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/vendorsearchdata",dataController.getvendorSearchdata)
router.post("/purchasehdrdata",dataController.getAllpurhdrData)
router.post("/addpurchasehdrdata",dataController.addpurchaseheader)
router.post("/purhdetData",dataController.getAllpurhdetData)
router.post("/addpurhdetData",dataController.addpurchasedetail)
router.post("/purtaxdata",dataController.getAllpurtaxData)
router.post("/purtaxdetail",dataController.addpurtaxdetail)
router.post("/TotalAmountCalculation",dataController.getTotalAmountCalculation)
router.post("/PartyCode",dataController.getPartyCode)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/addpurchasereturnheader",dataController.addpurchasereturnheader)
router.post("/getpurchrethdrdata",dataController.getAllpurchaseheaderreturnData)
router.post("/getpurchasereport",dataController.getpurchasereport)
router.post("/taxSearchdata",dataController.gettaxSearchdata)
router.post("/getitemcodepurdata",dataController.getitemcodepurdata)
router.post("/saleshdrdata",dataController.getAllsaleshdrData)
router.post("/addsaleshdrdata",dataController.addsaleshdr)
router.post("/addsalesdetData",dataController.addsalesdetdetail)
router.post("/addpurhdetData",dataController.addpurchasedetail)
router.post("/transactiontype",dataController.gettranstype)
router.post("/salestaxData",dataController.getAllsalestaxdetData)
router.post("/addsalestaxdetail",dataController.addsalestaxdetail)
router.post("/getPurchaseData",dataController.getPurchaseData)
router.post("/salessearchdata",dataController.getsalessearchdata)
router.post("/SalesRetHdrData",dataController.getAllSalesRetHdrData)
router.post("/addSalesRetHdr",dataController.addSalesRetHdr)
router.post("/getpurchasereturnit",dataController.getpurchasereturnit)
router.post("/getpurchasereturntax",dataController.getpurchasereturntax)
router.get("/Numberseries",dataController.getAllNumberseries)
router.post("/addNumberseries",dataController.addNumberseries)
router.post("/numberseriessearchdata",dataController.getnumberseriessearchdata)
router.post("/saveEditedNumberseriesData",dataController.saveEditedNumberseriesData)
router.post("/refNumberToHeaderPrintData",dataController.refNumberToHeaderPrintData)
router.post("/refNumberToDetailPrintData",dataController.refNumberToDetailPrintData)
router.post("/refNumberToSumTax",dataController.refNumberToSumTax)
router.post("/addpurchasereturntaxdetails",dataController.addpurchasereturntaxdetails)
router.post("/addpurchasereturndetails",dataController.addpurchasereturndetails)
router.post("/getpurchasereturndetails",dataController.getpurchasereturndetails)
router.post("/getpurchasereturntaxdetails",dataController.getpurchasereturntaxdetails)
router.post("/getAllDashboardData",dataController.getAllDashboardData)
router.post("/getSalesItemAmountCalculation",dataController.getSalesItemAmountCalculation)
router.post("/ItemPrice",dataController.getItemPrice)
router.post("/SalesTotalAmountCalculation",dataController.SalesTotalAmountCalculation)
router.post("/Product",dataController.getProduct)
router.post("/getPurchaseReturnItemAmountCalculation",dataController.getPurchaseReturnItemAmountCalculation)
router.post("/screentype",dataController.getscreentype)
router.post("/DashboardItemData",dataController.getDashboardItemData)
router.post("/DashboardStockData",dataController.getDashboardStockData)
router.post("/getsalesreport",dataController.getsalesreport)
router.post("/Passwords",dataController.Passwords)
router.post("/refNumberTosalesHeaderPrintData",dataController.refNumberTosalesHeaderPrintData)
router.post("/refNumberTosalesDetailPrintData",dataController.refNumberTosalesDetailPrintData)
router.post("/refNumberTosalesSumTax",dataController.refNumberTosalesSumTax)
// router.get("/getpurreturnkey ",dataController.getpurreturnkey )
router.post("/getitemstockvalue",dataController.getitemstockvalue )
router.post("/getAllItemVarient",dataController.getAllItemVarient )
router.post("/itemvairentname",dataController.getitemvairentname )
router.post("/DashboardUnit",dataController.getAllUOM )
router.post("/uomdetail",dataController.getAlluomdetail)
router.post("/numberseriesdeleteData",dataController.numberseriesdeleteData)
router.post("/onlywarehsearchdata",dataController.getonlywarehsearchdata)
router.post("/getusercompany",dataController.getusercompany)
router.post('/updateitemdata',dataController. updateitemData);
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.post("/getSalesReturnItemAmountCalculation",dataController.getSalesReturnItemAmountCalculation)
router.post("/getSalesData",dataController.getSalesData)
router.post("/getSalesDetail",dataController.getSalesDetail)
router.post("/getSalesTaxDetail",dataController.getSalesTaxDetail)
router.post("/getWarehouseCodeData",dataController.getWarehouseCodeData)
router.post("/SalesreturnTotalAmountCalculation",dataController.SalesreturnTotalAmountCalculation)
router.get("/userscreenmap", dataController.getAlluserscreenmap)
router.post("/adduserscreenmap",dataController.adduserscreenmap)
router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/getAllSalesRetDetailData",dataController.getAllSalesRetDetailData)
router.post("/addSalesRetDetail",dataController.addSalesRetDetail)
router.post("/addSalesRetTaxDetail",dataController.addSalesRetTaxDetail)
router.post("/getAllSalesRetTaxDetailData",dataController.getAllSalesRetTaxDetailData)
router.post("/customerhdr", dataController.getAllcustomerhdr)
router.post("/addcustomerhdr",dataController.addcustomerhdr)
router.get("/CustomerDetData", dataController.getAllCustomerDetData)
router.post("/addCustomerDetData",dataController.addCustomerDetData)
router.post("/updcustomerdetData",dataController.updcustomerdetData)
router.post("/customercode",dataController.getcustomercode)
router.post("/customerSearchdata",dataController.customerSearchdata)
router.post("/customerdeleteData",dataController.customerdeleteData)
router.post("/refNumberToPurchaseReturnHeaderPrintData",dataController.refNumberToPurchaseReturnHeaderPrintData)
router.post("/refNumberToPurchaseReturnDetailPrintData",dataController.refNumberToPurchaseReturnDetailPrintData)
router.post("/refNumberToPurachseReturnSumTax",dataController.refNumberToPurachseReturnSumTax)
router.post("/refNumberToSalesReturnHeaderPrintData",dataController.refNumberToSalesReturnHeaderPrintData)
router.post("/refNumberToSalesReturnDetailPrintData",dataController.refNumberToSalesReturnDetailPrintData)
router.post("/refNumberToSalesReturnSumTax",dataController.refNumberToSalesReturnSumTax)
router.post("/getItemCodeSalesData",dataController.getItemCodeSalesData)
router.post("/getCustomerCode",dataController.getCustomerCode)
router.post("/purdeletehdrData",dataController.purdeletehdrData)
router.post("/purDeleteDetailData",dataController.purDeleteDetailData)
router.post("/purDeleteTaxData",dataController.purDeleteTaxData)
router.post("/getUserPermission",dataController.getUserPermission)
router.post("/getPurchaseDeleteDetails", dataController.getPurchaseDeleteDetails)
router.post("/getpurDeleteDetails", dataController.getpurDeleteDetails)
router.post("/purdeletedunit", dataController.purdeletedunit)
router.post("/purdeletedtax", dataController.purdeletedtax)
router.post("/getRefSalesDelete", dataController.getRefSalesDelete);
router.post("/getsalesdelsearchdata", dataController.getsalesdelsearchdata);
router.post("/saledelsearchitem", dataController.saledelsearchitem);
router.post("/salesdelsearchtax", dataController.salesdelsearchtax);
router.post("/saledeletehdrData", dataController.saledeletehdrData);
router.post("/saleDeleteDetailData", dataController.saleDeleteDetailData);
router.post("/gettaxitemsales",dataController.gettaxitemsales)
router.post("/getDashboardPurchase",dataController.  getDashboardPurchase)
router.post("/getDashboardSales",dataController.getDashboardSales)
router.post("/getDashboardItemSales",dataController.  getDashboardItemSales)
router.post("/gettaxitempur",dataController.gettaxitempur)
router.post("/getCurrentStock",dataController.getCurrentStock)
router.post("/getNegativeStock",dataController.getNegativeStock) 
router.post("/salesDeleteTaxData",dataController.saleDeleteTaxData)
router.post("/warehouseDashboard",dataController.warehouseDashboard)
router.post("/deleteTaxData",dataController.deleteTaxData)
router.post("/updTaxdetData",dataController.updTaxdetData)
router.post("/getpurchasereturnView",dataController.getpurchasereturnView)
router.post("/UomChart",dataController.UomChart)
router.post("/TransDetail",dataController.Transdetail)
router.post("/partytransdetail",dataController.partytransdetail)
router.post("/alltransdetail",dataController.alltransdetail)
router.post("/datetransdetail",dataController.datetransdetail)
router.post("/getSalesreturnView",dataController.getSalesreturnView)
router.post("/getpurreturnsearchViewdata",dataController.getpurreturnsearchViewdata)
router.post("/getwarehousedrop",dataController.getwarehousedrop)
router.post("/varientChart",dataController.varientChart)
router.post("/getsalesreturnsearchViewdata",dataController.getsalesreturnsearchViewdata)
router.post("/SalesReturnTaxView",dataController.SalesReturnTaxView)
router.post("/SalesReturnDetailView",dataController.SalesReturnDetailView)
router.post("/getitemsalsearchdata",dataController.getitemsalsearchdata)
router.post("/gettransdetailchart",dataController.gettransdetailchart)
router.post("/getpurchasereturntaxView",dataController.getpurchasereturntaxView)
router.post("/getpurchasereturnitView",dataController.getpurchasereturnitView)
router.get("/getDateRange",dataController.getDateRange)
router.post("/getacctype",dataController.getacctype)
router.post("/getofftype",dataController.getofftype)
router.post("/addItemBrandData",upload.single('item_images'),dataController.addItemBrandData)
router.post("/getItemCodeQuotation",dataController.getItemCodeQuotation)
router.post("/getItem",dataController.getItem) 
router.post("/getItemCodeDcData",dataController.getItemCodeDcData) 
router.post("/purreturndeletehdrData",dataController.purreturndeletehdrData) 
router.post("/purreturndeletedetData",dataController.purreturndeletedetData) 
router.post("/purreturndeletetaxdetData",dataController.purreturndeletetaxdetData) 
router.post("/salereturndeletehdrData",dataController.salereturndeletehdrData) 
router.post("/salereturndeletedetData",dataController.salereturndeletedetData) 
router.post("/salereturndeletetaxdetData",dataController.salereturndeletetaxdetData)
router.post("/getAllsalesdetData",dataController.getAllsalesdetData) 
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/purchaseEditHeader",dataController.purchaseEditHeader)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/UserRole",dataController.getUserRole)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/getInventoryTransaction",dataController.getInventoryTransaction)
router.post("/getEmptype", dataController.getEmptype)
router.post("/Condition", dataController.getCondition)
router.post("/PurchaseAuthHdr", dataController.PurchaseAuthHdr)
router.post("/PurchaseAuthDetail", dataController.PurchaseAuthDetail)
router.post("/PurchaseAuthTaxDetail", dataController.PurchaseAuthTaxDetail)
router.post("/SalesAuthHdr", dataController.SalesAuthHdr)
router.post("/SalesAuthDetail", dataController.SalesAuthDetail)
router.post("/SalesAuthTaxDetail", dataController.SalesAuthTaxDetail)
router.post("/PurchReturnAuthHdr", dataController.PurchReturnAuthHdr)
router.post("/PurchReturnAuthDetail", dataController.PurchReturnAuthDetail)
router.post("/PurchReturnAuthTaxDetail", dataController.PurchReturnAuthTaxDetail)
router.post("/SalesReturnAuthHdr", dataController.SalesReturnAuthHdr)
router.post("/SalesReturnAuthDetail", dataController.SalesReturnAuthDetail)
router.post("/SalesReturnAuthTaxDetail", dataController.SalesReturnAuthTaxDetail)
router.post("/UpdateItemImage",upload.single('item_images'),dataController.UpdateItemImage)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/CompanyUpdate",upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/NumberSeriesUpdate", dataController.NumberSeriesUpdate)
router.post("/ItemUpdate",upload.single('item_images'),dataController.ItemUpdate)
router.post("/TaxUpdate", dataController.TaxUpdate)
router.post("/WarehouseUpdates", dataController.WarehouseUpdate)
router.post("/VendorUpdate", dataController.VendorUpdate)
router.post("/CustomerUpdate", dataController.CustomerUpdate)
router.post("/getEvent", dataController.getEvent)
router.post("/purauthstatus", dataController.purauthstatus)
router.post("/salauthstatus", dataController.salauthstatus)
router.post("/salretauthstatus", dataController.salretauthstatus)
router.post("/purretauthstatus", dataController.purretauthstatus)
router.post("/ItemAmountCalculation",dataController.getPurItemAmountCalculation)
router.post("/getsiblings",dataController.getsiblings)
router.post("/getKids",dataController.getkids)
router.post("/getMartial",dataController.getMartial)
router.post("/getSalaryType",dataController.getSalaryType)
router.post("/getPayscale",dataController.getPayscale)
router.post("/getLoanID",dataController.getLoanID)
router.post("/getDocumentType",dataController.getDocumentType)
router.post("/getCustomerDetails",dataController.getCustomerDetails)
router.post("/getrelation",dataController. getrelation)
router.post("/openingitemdelhdr",dataController.openingitemdelhdr)
router.post("/getallOIHdr",dataController.getallOIHdr)
router.post("/addOpeningItemDetail",dataController.addOpeningItemDetail)
router.post("/deleteOpeningItemDetail",dataController.deleteOpeningItemDetail)
router.post("/allOpeningItemDetail",dataController.allOpeningItemDetail)
router.post("/getallOpeningItem",dataController.getallOpeningItem)
router.post("/openingItemSearch",dataController.openingItemSearch)
router.post("/getallOpeningItemDetail",dataController.getallOpeningItemDetail)
router.post("/getcompanyshift",dataController.getcompanyshift)
router.post("/getItemCodeSalesDataQuote",dataController.getItemCodeSalesDataQuote)
router.post("/getotherpurtax",dataController.getotherpurtax)
router.post("/getothersalestax",dataController.getothersalestax)
router.post("/getOverallTAX",dataController.getOverallTAX)
router.post("/getItemCodeOtherSalesData",dataController.getItemCodeOtherSalesData)
router.post("/getInvocieType",dataController.getInvocieType)
router.post("/getVendorDetails",dataController.getVendorDetails)
router.post("/getItemCodeSalesDatatest",dataController.getItemCodeSalesDatatest)
router.post("/getcodetest",dataController.getcodetest)
router.post("/getCodeSalesDatatest",dataController.getCodeSalesDatatest)
router.post("/getitemsalsearchdatatest",dataController.getitemsalsearchdatatest)
router.post("/getLeaveType",dataController.getLeaveType)
router.post("/getSelectSlot",dataController.getSelectSlot)
router.post("/getGstReportAnalysis",dataController.getGstReportAnalysis)
router.post("/getDashBoardType",dataController.getDashBoardType)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getItemCode",dataController.getItemCode)
router.post("/getOpeningItemPeriod",dataController.getOpeningItemPeriod)
router.post("/getType",dataController.getType)
router.post("/getAccrual",dataController.getAccrual)
router.post("/getExceedLeave",dataController.getExceedLeave)
router.post("/getLeaveReason",dataController.getLeaveReason)
router.post("/getCustomerCodeDrop",dataController.getCustomerCodeDrop)
router.post("/getPendingStatus",dataController.getPendingStatus)
router.post("/getDateWiseItemStock",dataController.getDateWiseItemStock)
router.post("/getdefCustomer",dataController.getdefCustomer)
router.post("/getitemcodevariant",dataController.getitemcodevariant)
router.post("/getDefaultoptions",dataController.getDefaultoptions)
router.post("/getSalesMode",dataController.getSalesMode)
router.post("/getSalesReturnAmountCalculation",dataController.getSalesReturnAmountCalculation)
router.post("/AddTransactionSettinngs",dataController.AddTransactionSettinngs)
router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
router.post("/getTaskstatus",dataController.getTaskstatus)
router.post("/PendingCustomer",dataController.PendingCustomer)
router.post("/getPriority",dataController.getPriority)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/getboolean", dataController.getboolean)
router.post("/getDocument",dataController.getDocument)
router.post("/updateRoleRights",dataController.updateRoleRights)
router.post("/getnegstock",dataController.getnegstock)
router.post("/getPrint",dataController.getPrint)
router.post("/getcopies",dataController.getcopies)
router.post("/AddPrintTemplate", dataController.AddPrintTemplate)
router.post("/salesTermsandCondition",dataController.salesTermsandCondition)
router.post("/deleteSalesTermsandCondition",dataController.deleteSalesTermsandCondition)
router.get("/getAllSalesTermsandCondition",dataController.getAllSalesTermsandCondition)
router.post("/termsandCondition",dataController.termsandCondition)
router.post("/getTermsandConditionSales",dataController.getTermsandConditionSales)
router.post("/getDeletedTermsSales",dataController.getDeletedTermsSales)
router.post("/Templatesearch",dataController.Templatesearch)
router.post("/customerCodeDropdown",dataController.customerCodeDropdown)
router.post("/PrintTemplates",dataController.PrintTemplates)
router.post("/vendorCodeDropdown",dataController.vendorCodeDropdown)
router.post("/getSalesItemCode",dataController.getSalesItemCode)
router.post("/addSalesOrderHdr",dataController.addSalesOrderHdr)
router.post("/getSalesOrderHdr",dataController.getSalesOrderHdr)
router.post("/salesOrderSearchData",dataController.salesOrderSearchData)
router.post("/deleteSalesOrderHdr",dataController.deleteSalesOrderHdr)
router.post("/deletedSalesOrderSearchData",dataController.deletedSalesOrderSearchData)
router.post("/addSalesOrderDetail",dataController.addSalesOrderDetail)
router.post("/deleteSalesOrderDetail",dataController.deleteSalesOrderDetail)
router.post("/getSalesOrderDetail",dataController.getSalesOrderDetail)
router.post("/addSalesOrderTaxDet",dataController.addSalesOrderTaxDet)
router.post("/deleteSalesOrderTaxDet",dataController.deleteSalesOrderTaxDet)
router.post("/getSalesOrderTaxDet",dataController.getSalesOrderTaxDet)
router.post("/addPurchaseOrderHdr",dataController.addPurchaseOrderHdr)
router.post("/deletePurchaseOrderHdr",dataController.deletePurchaseOrderHdr)
router.post("/PurchaseOrderSearchData",dataController.PurchaseOrderSearchData)
router.post("/deletedPurchaseOrderSearchData",dataController.deletedPurchaseOrderSearchData)
router.post("/getPurchaseOrderHdr",dataController.getPurchaseOrderHdr)
router.post("/addPurchaseOrderDetail",dataController.addPurchaseOrderDetail)
router.post("/deletePurchaseOrderDetail",dataController.deletePurchaseOrderDetail)
router.post("/getPurchaseOrderDetail",dataController.getPurchaseOrderDetail)
router.post("/addPurchaseOrderTaxDet",dataController.addPurchaseOrderTaxDet)
router.post("/deletePurchaseOrderTaxDet",dataController.deletePurchaseOrderTaxDet)
router.post("/getPurhaseOrderTaxDet",dataController.getPurhaseOrderTaxDet)
router.post("/getPurchaseOrder",dataController.getPurchaseOrder)
router.post("/getDeletedPurchaseOrder",dataController.getDeletedPurchaseOrder)
router.post("/getSalesOrder",dataController.getSalesOrder)
router.post("/getDeletedSalesOrder",dataController.getDeletedSalesOrder)
router.post("/getPODetail",dataController.getPODetail)
router.post("/getDeletedPODetail",dataController.getDeletedPODetail)
router.post("/getPOTaxDetail",dataController.getPOTaxDetail)
router.post("/getDeletedPOTaxDetail",dataController.getDeletedPOTaxDetail)
router.post("/getSODetail",dataController.getSODetail)
router.post("/getDeletedSODetail",dataController.getDeletedSODetail)
router.post("/getSOTaxDetail",dataController.getSOTaxDetail)
router.post("/getDeletedSOTaxDetail",dataController.getDeletedSOTaxDetail)
router.post("/printPOHeader",dataController.printPOHeader)
router.post("/printPODetail",dataController.printPODetail)
router.post("/printPOTaxDetail",dataController.printPOTaxDetail)
router.post("/printSOHeader",dataController.printSOHeader)
router.post("/printSODetail",dataController.printSODetail)
router.post("/printSOTaxDetail",dataController.printSOTaxDetail)
router.post("/Item_Category_MasterInsert", upload.single('Item_Category_Image'),dataController.Item_Category_MasterInsert)
router.post("/Item_Category_MasterUpdate",upload.single('Item_Category_Image'),dataController.Item_Category_MasterUpdate)
router.post("/Item_Category_MasterDelete",dataController.Item_Category_MasterDelete)
router.post("/Categorysearch",dataController.Categorysearch)
router.post("/getDefault",dataController.getDefault)
router.post("/CategoryFetch",dataController.CategoryFetch)
router.post("/Item_Category_MasterUpdateRow",dataController.Item_Category_MasterUpdateRow)
router.post("/openingitemhdr",dataController.openingitemhdr)
router.post("/getCurrentStockItemCode",dataController.getCurrentStockItemCode)
router.post("/getTotalStockValueDetails",dataController.getTotalStockValueDetails)




module.exports = router;
     
